version: "3"

services:
  app:
    build: .
    container_name: app
    entrypoint: dockerize -template .docker/env-example:.env -wait tcp://db:3306 --timeout 60s ./entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=teste
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/code
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=teste
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
